### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Feliix42** [fsr/course-management#63]
I'd like to implement some kind of logging to address @JustusAdam's concerns regarding abuse (see #51) and allow users to delete their accounts.

I think, the following points should be logged:
- [ ] User Creation
- [ ] User Deletion
- [x] Enrolling for a course
- [x] Unenrolling from a course
- [x] Forced unenrolling from a course
- [ ] Verification of a user account
- [ ] Password changes (in case an account was hacked - of course no plain text passwords!)

Therefore it would be a good thing to take care of #56 to assure our users we are handling their data responsibly.

Any opinions?

**Comment by Feliix42** [comment]
See #65.
